# Evaluation Configuration for RBM (Robometer)
# This config is used specifically for evaluation runs

# Model path to load training config from
# model_path: "aliangdw/rbm_prefprog_v4"  # Path to the trained model checkpoint (will load training_config.yaml from here)
# model_path: "aliangdw/rewind-libero-mw-pp-balanced"
# model_path: "aliangdw/rewind-base-mw-only"
model_path: "rewardfm/ant-rfm-rewind-bs1024-pref-prog-sim"

# GPU Pool settings
num_gpus: 1  # Number of GPUs to use (null for all available)
max_workers: 8 # Max worker threads (null for auto, typically same as num_gpus)

# Evaluation parameters
batch_size: 4  # Batch size for evaluation
server_url: "0.0.0.0"  # Evaluation server URL
server_port: 8000  # Evaluation server port