# config.yaml
dataset:
  dataset_path: ./datasets/auto_eval  # Root containing eval_data/
  dataset_name: auto_eval_rfm

output:
  output_dir: ./robometer_dataset/auto_eval_rfm
  max_trajectories: -1
  max_frames: 64
  use_video: true
  fps: 5
  shortest_edge_size: 240
  center_crop: false
  num_workers: 4

hub:
  push_to_hub: true
  hub_repo_id: auto_eval_rfm


