# config.yaml
dataset:
  dataset_path: ./datasets/epic_kitchens
  dataset_name: epic

output:
  output_dir: ./rfm_dataset/epic_rfm
  max_trajectories: -1
  max_frames: 64
  use_video: true
  fps: 30
  shortest_edge_size: 240
  center_crop: false
  num_workers: 4

hub:
  push_to_hub: true
  hub_repo_id: epic_rfm


