# config.yaml
dataset:
  dataset_path: ./datasets/galaxea   # Root containing 'rlds/'
  dataset_name: galaxea

output:
  output_dir: ./rfm_dataset/galaxea_rfm
  max_trajectories: -1
  max_frames: 64
  use_video: true
  fps: 15
  shortest_edge_size: 240
  center_crop: false
  num_workers: 8

hub:
  push_to_hub: true
  hub_repo_id: galaxea_rfm


