# config.yaml
dataset:
  dataset_path: ./datasets/hand_paired_data
  dataset_name: hand_paired

output:
  output_dir: ./robometer_dataset/hand_paired_rfm
  max_trajectories: -1
  max_frames: 64
  use_video: true
  fps: 10
  shortest_edge_size: 240
  center_crop: false
  num_workers: 4

hub:
  push_to_hub: true
  hub_repo_id: hand_paired_rfm

