# Humanoid Everyday dataset configuration
dataset:
  dataset_path: "./datasets/humanoid_everyday"  # Path containing zip files with humanoid everyday datasets
  dataset_name: humanoid_everyday_rfm

output:
  output_dir: ./robometer_dataset/humanoid_everyday_rfm
  max_trajectories: -1
  max_frames: 64
  use_video: true
  fps: 30
  shortest_edge_size: 240
  center_crop: false
  num_workers: 4

hub:
  push_to_hub: true
  hub_repo_id: humanoid_everyday_rfm
