# config.yaml
dataset:
  dataset_path: ./datasets/molmoact   # Root containing parquet files
  dataset_name: molmoact

output:
  output_dir: ./rfm_dataset/molmoact_rfm
  max_trajectories: -1
  max_frames: 64
  use_video: true
  fps: 10
  shortest_edge_size: 240
  center_crop: false
  num_workers: 1

hub:
  push_to_hub: true
  hub_repo_id: molmoact_rfm


