# RFM-MIT-Franka Dataset Configuration
dataset:
  dataset_path: ~/reward_fm/datasets/RFM_MIT_Franka  # Path to dataset directory
  dataset_name: rfm_new_mit_franka_rfm

output:
  output_dir: ./rfm_dataset/rfm_new_mit_franka_rfm
  max_trajectories: -1  # -1 for all trajectories
  max_frames: 32
  use_video: true
  fps: 10
  shortest_edge_size: 240
  center_crop: false
  num_workers: 4

hub:
  push_to_hub: true
  hub_repo_id: rfm_new_mit_franka_rfm
