# UTD SO101 Human dataset config
dataset:
  dataset_path: ./raw_data/RFM_UTD_Human
  dataset_name: utd_so101_human

output:
  output_dir: ./rfm_dataset/utd_so101_human
  max_trajectories: -1
  max_frames: 64
  use_video: true
  fps: 10
  shortest_edge_size: 240
  center_crop: false
  num_workers: 2

hub:
  push_to_hub: false
  hub_repo_id: utd_so101_human