# USC xArm Policy Ranking dataset config
dataset:
  dataset_path: ./xarm_policy_ranking
  dataset_name: usc_xarm_policy_ranking

output:
  output_dir: ./rfm_dataset/usc_xarm_policy_ranking
  max_trajectories: -1
  max_frames: 64
  use_video: true
  fps: 10
  shortest_edge_size: 240
  center_crop: false
  num_workers: 1

hub:
  push_to_hub: false
  hub_repo_id:

