train_datasets:
  - "aliangdw/metaworld"

train_subsets:
  - ["metaworld_train"]

eval_datasets:
  - "jesbu1/mit_franka_p-rank_rfm"
  - "jesbu1/utd_so101_clean_policy_ranking_top"
  - "jesbu1/utd_so101_clean_policy_ranking_wrist"

eval_subsets:
  - ["mit_franka_p-rank_rfm"]
  - ["utd_so101_clean_policy_ranking_top"]
  - ["utd_so101_clean_policy_ranking_wrist"]

max_frames_for_preprocessing: 32
video_frame_sampling: "uniform"
num_proc: 1
num_threads: 8
force_reprocess: false
cache_dir: /scr/shared/reward_fm/processed_datasets

# Embedding preprocessing parameters
precompute_embeddings: true
embeddings_cache_dir: "embeddings"
dinov2_model: "facebook/dinov2-base"
sentence_model: "sentence-transformers/all-MiniLM-L12-v2"
embedding_batch_size: 64
