train_datasets:
  # - "abraranwar/libero_rfm"
  # - "ykorkmaz/libero_failure_rfm"
  # - "HenryZhang/metaworld_rewind_rfm_train"
  - "aliangdw/metaworld"

train_subsets:
  # - ["libero256_90"]
  # - ["libero_90_failure"]
  # - ["metaworld_rewind_train"]
  - ["metaworld_train"]

eval_datasets:
  # - "abraranwar/libero_rfm"
  # - "ykorkmaz/libero_failure_rfm"
  # - "HenryZhang/metaworld_rewind_rfm_eval"
  - "aliangdw/metaworld"

eval_subsets:
  # - ["libero256_10"]
  # - ["libero_10_failure"]
  - ["metaworld_eval"]
  # - ["metaworld"]

max_frames_for_preprocessing: 64
video_frame_sampling: "uniform"
num_proc: 1
num_threads: 32
force_reprocess: false
cache_dir: /scr/shared/reward_fm/processed_datasets

# Embedding preprocessing parameters
precompute_embeddings: true
embeddings_cache_dir: "embeddings"
dinov2_model: "facebook/dinov2-base"
sentence_model: "sentence-transformers/all-MiniLM-L12-v2"
embedding_batch_size: 32