# RFM VQA
trainer_cls: "rfm_vqa"

model:
  model_type: "vqa"

data:  
  sample_type_ratio: [1, 1, 0] # preference, progress, similarity

training:  
  output_dir: "./logs/rfm_vqa"

logging:
  wandb_project: "rfm"
  wandb_entity: clvr
  wandb_run_name: "rfm_vqa"